site_name: Cooking
copyright: Copyright &copy; 2024 GlasVader

theme:
  font:
    text: Roboto
  name: material
  include_search_page: false
  search_index_only: true
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tertiary
    - navigation.footer
    - toc.follow
    - page.toc
    - search.suggest
    - search.highlight
    - search.share
    # - header.autohide # cool feature, but nav and toc remain at their positions, leaving a funny gap
    - content.footnote.tooltips # does not work?

markdown_extensions:
  - attr_list
  - abbr
  - admonition
  - def_list
  - md_in_html
  - footnotes # does not work?
  - tables
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
      - name: flow
        class: uml-flowchart
        format: superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
    - search
    # - pdf-export:
    #     verbose: true
    #     media_type: print
    #     enabled_if_env: ENABLE_PDF_EXPORT

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - General:
    - Start: index.md #must remain here
    - Testarea Syntax: general/testarea/testarea.md

    - Science of Cooking:
      - Thermodynamics of Boiling: general/science_of_cooking/thermodynamics/thermodynamics_of_boiling.md
  #   - Oils:
    
  #   - Vegetables:

  #   - Meat:

  #     - Beef:

  #     - Pork:

  #     - Chicken:


  # - Country specific:

  #   - German:

  #   - Italian:

  #   - French:

  #   - Spanish:

  #   - Indian:
  
  - Pizza: 
    - Overview: pizza/index.md
    - Napoletana: pizza/napoletana/napoletana.md
